version: '3.5'

services:
  app:
    build: .
    volumes:
     - ./:/usr/src/app/
    ports:
      - "80:80"
      - "1337:1337"

  test:
    build: testing/
    volumes:
     - ./testing:/usr/src/testing/
    depends_on:
     - app
