version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"

  app:
    build: .
    volumes:
     - ./:/usr/src/app/
    expose:
     - "8000"
     - "8100"
     - "8200"
     - "8300"
     - "8400"
     - "8500"
     - "8600"
     - "8700"
     - "8800"
     - "8900"
     - "9000"
