version: '3.5'
services:
  hub:
    image: selenium/hub:3.141.59-mercury
    ports:
      - "4444:4444"

  firefox:
    build:
      context: .
      shm_size: '2gb'
    volumes:
      - /dev/shm:/dev/shm
      - ./:/usr/src/app
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
