# Use the production image as base image
FROM nodejscardgame_app:latest

# Create test directory
WORKDIR /usr/src/test

# Override the NODE_ENV environment variable to 'dev', in order to get required test packages
ENV NODE_ENV dev

# 1. Get test packages; AND
# 2. Install our test framework - mocha
RUN npm update && \
    npm install -g mocha

# Override the command, to run the test instead of the application
CMD ["mocha", "mocha_tests.js", "--reporter", "spec"]
